server:
  port: 7701
spring:
  application:
    name: eureka-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/QiQingLin/eureka-config.git
          search-paths: /**
          username: qiqinglin7@gmail.com
          password: Zaqzaq770
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7707/eureka/