eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7707/eureka/
server:
  port: 5000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: service-user
          uri: lb://SERVICE-USER
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
            - RequestTime=true
